# -*- coding: utf-8 -*-
"""descion tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3IycHzpJ1bfLUqFdF6wRnbHbGQjwNEG
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

def preprocess_and_evaluate(file_path):
    # Load dataset
    data = pd.read_csv(file_path)

    # Categorize 'confidence' into Low, Medium, High
    def categorize_confidence(conf):
        if conf < 50:
            return "Low"
        elif 50 <= conf <= 80:
            return "Medium"
        else:
            return "High"

    data['confidence_category'] = data['confidence'].apply(categorize_confidence)

    # Feature selection
    features = ['brightness', 'latitude', 'longitude', 'frp', 'bright_t31']
    target = 'confidence_category'

    # Encode the categorical target variable
    label_encoder = LabelEncoder()
    data['confidence_encoded'] = label_encoder.fit_transform(data[target])

    # Split the data into training and testing sets
    X = data[features]
    y = data['confidence_encoded']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the Decision Tree model
    clf = DecisionTreeClassifier(random_state=42)
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred, target_names=label_encoder.classes_)
    confusion_mat = confusion_matrix(y_test, y_pred)

    # Visualization - Confusion Matrix
    plt.figure(figsize=(8, 6))
    sns.heatmap(confusion_mat, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
    plt.title('Confusion Matrix')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

    # Visualization - Histograms for Features
    for feature in features:
        plt.figure(figsize=(8, 4))
        sns.histplot(data[feature], bins=30, kde=True, color='green')
        plt.title(f'Distribution of {feature}')
        plt.xlabel(feature)
        plt.ylabel('Frequency')
        plt.show()

    # Output results
    return {
        "accuracy": accuracy,
        "classification_report": classification_rep,
        "confusion_matrix": confusion_mat
    }

# Example usage
file_path = '/content/modis_2023_Brazil.csv'
results = preprocess_and_evaluate(file_path)
print("Accuracy:", results['accuracy'])
print("\nClassification Report:\n", results['classification_report'])
print("\nConfusion Matrix:\n", results['confusion_matrix'])