# -*- coding: utf-8 -*-
"""Neural Networks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ckgaXqGPKNwx_wfKz8BNVkPsyI5HTSR
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import matplotlib.pyplot as plt
import seaborn as sns

def preprocess_and_evaluate_neural_network(file_path):
    try:
        # Load dataset
        data = pd.read_csv(file_path, sep=',')
    except pd.errors.ParserError as e:
        print(f"Error reading CSV: {e}")
        with open(file_path, 'r') as f:
            for i, line in enumerate(f):
                print(f"Problematic line {i + 1}: {line}")
        return
    except Exception as e:
        print("Error loading file:", e)
        return

    # Categorize 'confidence' into Low, Medium, High
    def categorize_confidence(conf):
        if conf < 50:
            return "Low"
        elif 50 <= conf <= 80:
            return "Medium"
        else:
            return "High"

    data['confidence_category'] = data['confidence'].apply(categorize_confidence)

    # Feature selection
    features = ['brightness', 'latitude', 'longitude', 'frp', 'bright_t31']
    target = 'confidence_category'

    # Handle missing values
    data = data.dropna(subset=features + [target])

    # Encode the categorical target variable
    label_encoder = LabelEncoder()
    data['confidence_encoded'] = label_encoder.fit_transform(data[target])

    # Standardize the features
    scaler = StandardScaler()
    data[features] = scaler.fit_transform(data[features])

    # Split the data into training and testing sets
    X = data[features]
    y = data['confidence_encoded']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Build the Neural Network model
    model = Sequential()
    model.add(Dense(64, input_dim=len(features), activation='relu'))
    model.add(Dropout(0.3))
    model.add(Dense(32, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(len(label_encoder.classes_), activation='softmax'))

    # Compile the model
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Train the model
    history = model.fit(X_train, y_train, epochs=50, batch_size=16, validation_data=(X_test, y_test), verbose=1)

    # Evaluate the model
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    y_pred = model.predict(X_test)
    y_pred_classes = y_pred.argmax(axis=1)

    classification_rep = classification_report(y_test, y_pred_classes, target_names=label_encoder.classes_)
    confusion_mat = confusion_matrix(y_test, y_pred_classes)

    # Visualization - Confusion Matrix
    plt.figure(figsize=(8, 6))
    sns.heatmap(confusion_mat, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
    plt.title('Confusion Matrix')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

    # Visualization - Training and Validation Loss and Accuracy
    plt.figure(figsize=(12, 5))

    # Plot Loss
    plt.subplot(1, 2, 1)
    plt.plot(history.history['loss'], label='Training Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.title('Model Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    # Plot Accuracy
    plt.subplot(1, 2, 2)
    plt.plot(history.history['accuracy'], label='Training Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.title('Model Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.show()

    # Output results
    return {
        "accuracy": accuracy,
        "classification_report": classification_rep,
        "confusion_matrix": confusion_mat
    }

# Example usage
file_path = '/content/modis_2023_Brazil.csv'
results = preprocess_and_evaluate_neural_network(file_path)
if results:
    print("Accuracy:", results['accuracy'])
    print("\nClassification Report:\n", results['classification_report'])
    print("\nConfusion Matrix:\n", results['confusion_matrix'])