# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7Tkcgi9_qjhgb-7QpRKI9p-RRPGBjJO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

data = pd.read_excel('/content/modis_2023_Brazil.xlsx', sheet_name='modis_2023_Brazil.csv')

# Preprocessing
# Drop unnecessary columns (assuming 'type' is the target)
data = data.drop(columns=['latitude', 'longitude', 'acq_date', 'satellite', 'instrument', 'version'])

# Encode categorical variables
label_encoder = LabelEncoder()
data['daynight'] = label_encoder.fit_transform(data['daynight'])

# Handle missing values (if any)
data = data.dropna()

# Split features and target
X = data.drop(columns=['type'])
y = data['type']

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Random Forest with hyperparameter tuning
rf = RandomForestClassifier(random_state=42)
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

from sklearn.model_selection import GridSearchCV

# Define a smaller parameter grid
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

# Define GridSearchCV with fewer folds
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=2, scoring='accuracy', n_jobs=-1)

# Fit the model
grid_search.fit(X_train, y_train)

# Retrieve the best parameters and score
best_params = grid_search.best_params_
best_score = grid_search.best_score_
print("Best Parameters:", best_params)
print("Best Accuracy:", best_score)

best_rf = grid_search.best_estimator_ # Assign the best estimator to best_rf

if best_rf:
    y_pred = best_rf.predict(X_test)
    conf_matrix = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues",
                xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted') # Use 'weighted' for multi-class
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")

    # Classification Report
print(classification_report(y_test, y_pred))

    # ROC AUC Score (if applicable, requires probability estimates)
try:
        y_prob = best_rf.predict_proba(X_test)
        roc_auc = roc_auc_score(y_test, y_prob, multi_class='ovr') # Use 'ovr' for multi-class
        print(f"ROC AUC Score: {roc_auc}")
except Exception as e:
        print(f"ROC AUC Score could not be calculated: {e}")
else:
    print("Confusion matrix and other metrics cannot be calculated as the model training failed.")